# Generated by Django 5.2.12 on 2026-03-15 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LanDieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=200, verbose_name='Tên làn điệu')),
                ('mo_ta_y_nghia', models.TextField(blank=True, null=True, verbose_name='Mô tả ý nghĩa')),
                ('nguon_goc', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nguồn gốc')),
            ],
            options={
                'verbose_name': 'Làn điệu',
                'verbose_name_plural': 'Các Làn điệu',
            },
        ),
        migrations.CreateModel(
            name='NgheNhan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=200, verbose_name='Tên nghệ nhân')),
                ('nam_sinh', models.IntegerField(blank=True, null=True, verbose_name='Năm sinh')),
                ('danh_hieu', models.CharField(blank=True, max_length=100, null=True, verbose_name='Danh hiệu')),
                ('tieu_su', models.TextField(blank=True, null=True, verbose_name='Tiểu sử')),
                ('anh_dai_dien', models.ImageField(blank=True, null=True, upload_to='nghe_nhan/', verbose_name='Ảnh đại diện')),
            ],
            options={
                'verbose_name': 'Nghệ nhân',
                'verbose_name_plural': 'Các Nghệ nhân',
            },
        ),
        migrations.CreateModel(
            name='BaiHat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_bai', models.CharField(max_length=255, verbose_name='Tên bài hát')),
                ('loi_bai_hat', models.TextField(blank=True, null=True, verbose_name='Lời bài hát')),
                ('file_audio', models.URLField(blank=True, null=True, verbose_name='Link Audio/YouTube')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audios/', verbose_name='File Audio (MP3/WAV)')),
                ('youtube_url', models.URLField(blank=True, null=True, verbose_name='Link YouTube (để nhúng video)')),
                ('favorites', models.ManyToManyField(blank=True, related_name='favorite_songs', to=settings.AUTH_USER_MODEL, verbose_name='Lượt yêu thích')),
                ('lan_dieu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bai_hats', to='culture.landieu', verbose_name='Làn điệu')),
                ('nghe_nhan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bai_hats', to='culture.nghenhan', verbose_name='Nghệ nhân trình bày')),
            ],
            options={
                'verbose_name': 'Bài hát',
                'verbose_name_plural': 'Các Bài hát',
            },
        ),
    ]
