# Generated by Django 5.2.12 on 2026-03-15 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaiViet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieu_de', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('hinh_anh', models.ImageField(blank=True, null=True, upload_to='bai_viet/%Y/%m/', verbose_name='Hình ảnh bìa')),
                ('tom_tat', models.TextField(blank=True, null=True, verbose_name='Tóm tắt')),
                ('noi_dung', models.TextField(verbose_name='Nội dung')),
                ('ngay_dang', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đăng')),
                ('nguoi_dang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người đăng')),
            ],
            options={
                'verbose_name': 'Bài viết (Tin tức)',
                'verbose_name_plural': 'Các Bài viết',
            },
        ),
    ]
