# Generated by Django 5.2.12 on 2026-03-15 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0002_baiviet'),
    ]

    operations = [
        migrations.CreateModel(
            name='LangQuanHo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_lang', models.CharField(max_length=200, verbose_name='Tên làng')),
                ('huyen', models.CharField(help_text='Ví dụ: TP Bắc Ninh, Tiên Du, Yên Phong...', max_length=150, verbose_name='Huyện/Thị xã')),
                ('mo_ta', models.TextField(blank=True, null=True, verbose_name='Lịch sử/Đặc điểm làng')),
            ],
            options={
                'verbose_name': 'Làng Quan Họ',
                'verbose_name_plural': 'Các Làng Quan Họ',
            },
        ),
        migrations.RemoveField(
            model_name='baihat',
            name='file_audio',
        ),
        migrations.AddField(
            model_name='baihat',
            name='mo_ta_hoan_canh',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả thông tin bổ sung'),
        ),
        migrations.AlterField(
            model_name='nghenhan',
            name='tieu_su',
            field=models.TextField(blank=True, null=True, verbose_name='Tiểu sử/Mô tả'),
        ),
        migrations.AddField(
            model_name='nghenhan',
            name='lang_que',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nghe_nhans', to='culture.langquanho', verbose_name='Thuộc Làng'),
        ),
    ]
