# Generated by Django 5.2.12 on 2026-03-15 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0003_langquanho_remove_baihat_file_audio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='langquanho',
            name='anh_dai_dien',
            field=models.ImageField(blank=True, null=True, upload_to='lang_quan_ho/', verbose_name='Ảnh đại diện làng'),
        ),
    ]
